### ISSUE TITLE
Please write a post-processing script to add Bibls and a @source citation attribute and value

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#1]
Sorry I posted this here: https://github.com/srophe/srophe-app-data/issues/778

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Not sure if you saw?
Here is the first pass at the script.
https://github.com/srophe/util/blob/master/add-bibl.xql

Let me know if there are any issues.

**Comment by davidamichelson** [comment]
Need to run this and add in the data

**Comment by wlpotter** [comment]
@wsalesky This script seems to be working correctly for adding sources to abstracts. I am having a little trouble getting it to work for adding sourced tei:locations, particularly when reading in TSV from files. Since the data sources for each functionality are in two separate TSV files anyway, would it be possible to split this into two scripts? 

One script would add source attributes and tei:bibls for abstracts based on a two-column TSV data source (record URI | bibl URI).

Another script would add sourced tei:locations and tei:bibls from a three-column TSV data source (record URI | location | bibl URI). I can make a second issue for this script if you would like?

Thanks!

**Comment by wsalesky** [comment]
@wlpotter can I have some sample data with the location? This script should work, there must be a bug in how it recognizes the location. I would rather keep them together in this script and just fix the bug.

**Comment by davidamichelson** [comment]
@wsalesky I'd prefer to have two separate scripts for our future use in a script library. Eg, Script 1 = Add Coordinates, Script 2 =Add Citation to Abstract. We are also anticipating a third script that adds a different kind of location data, so we would like to have separate scripts for each kind of data we want to add. Thanks!

**Comment by wlpotter** [comment]
BQURI | Lat-Long | BIBLURI
-- | -- | --
10 | 36.200663 36.165318 | https://pleiades.stoa.org/places/658381
105 | 31.870028 35.443871 | http://pleiades.stoa.org/places/687917
109 | 35.972501 39.08287 | http://pleiades.stoa.org/places/668318
111 | 32.5 46.5 | http://pleiades.stoa.org/places/912880
122 | 36.526118 37.954539 | http://pleiades.stoa.org/places/658480
129 | 37.39206 46.23909 | http://gazetteer.dainst.org/place/2733333
136 | 38.382217 38.361152 | http://pleiades.stoa.org/places/629040
139 | 36.335572 43.13713 | http://pleiades.stoa.org/places/874609
142 | 37.067234 41.215055 | http://pleiades.stoa.org/places/874623
143 | 34.025421 36.73461199999997 | http://pleiades.stoa.org/places/678085

**Comment by wlpotter** [comment]
Here is a sample of coordinate data

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Should this just add a new location element? What about when there is already a location element with coordinates?

**Comment by wlpotter** [comment]
@wsalesky I believe we decided for now to have it just add a new location element, even when there is already a location element.

We will have to mark one as `@subtype="preferred"` and there may be cases (particularly for Pleiades) where the coordinates and source are the same. But I think we decided to handle those cases later.

@davidamichelson do I have that right?

**Comment by wsalesky** [comment]
Done. See: https://github.com/srophe/util/blob/master/add-location.xql

**Comment by wlpotter** [comment]
I ran the script and pushed the added data; I believe this issue is complete.
