### ISSUE TITLE
Merge duplicate names by String

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#10]

**Comment by davidamichelson** [comment]
Mainly in the 5000s

**Comment by davidamichelson** [comment]
@wsalesky Could you please write a script that does the following? We would like to save it where we keep our data maintenance scripts.

The script will evaluate all /TEI/text/body/listPlace/place/placeName

When it finds any example where both placeName() and placeName/@lang() match  placeName() and placeName/@xml:lang() of another TEI:placeName, it will merge the two into one.

An example is record 5007:
Current:
```
          <placeName xml:id="name5007-2" xml:lang="ar" srophe:tags="#headword" resp="http://bqgazetteer.bethmardutho.org">الأبطح</placeName>
          <placeName xml:id="name5007-3" xml:lang="ar" source="#bib5007-1">الأبطح</placeName>
```
After script should be:
```
          <placeName xml:id="name5007-2" xml:lang="ar" srophe:tags="#headword" resp="http://bqgazetteer.bethmardutho.org" source="#bib5007-1">الأبطح</placeName>
```

In otherwords, name5007-3 is deleted and only name5007-2 remains but with the attribute values of both name5007-3 and name5007-2

In most cases there are only going to be two placeNames to merge, but in theory there could be more. It is important that both the string value of placeName() and also the value of the @xml:lang match since matching only on placeName() could give a false positive when say the French and English version of the names has the same value.

**Comment by davidamichelson** [comment]
@wsalesky Any update on this script?

**Comment by wsalesky** [comment]
@davidamichelson Sorry for the long delay. I have this script ready. The current version runs on all names and can be found here:  https://github.com/srophe/util/blob/master/merge-names.xql

**Comment by wlpotter** [comment]
@wsalesky The script worked great! This should be fixed.
