### ISSUE TITLE
Check Islands (Waiting to hear from Mario)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#11]
Where are they? Ex record 3008

**Comment by wlpotter** [comment]
Make sure they have coordinates. (Wait to check this until after coordinates added, see #3)

**Comment by davidamichelson** [comment]
Why are there 40 islands in Syriac browse and only 1 in English?

**Comment by wsalesky** [comment]
Looks like a browse bug. I will take a look at it.

**Comment by wsalesky** [comment]
I think this has been resolved on https://github.com/srophe/bethqatraye/issues/44

**Comment by wlpotter** [comment]
See this "Islands" tab of this Google Sheet: https://docs.google.com/spreadsheets/d/1ynw6GCpJxBdVRy-0LoMvOgISFOmWGEM-9e0r2JWIsb4/edit#gid=1283333378

Need coordinates for those still lacking them.
