### ISSUE TITLE
Delete XML ID from place elements?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#19]
Example: place xml:id="place-3015"

Discuss with Dan

**Comment by dlschwartz** [comment]
@davidamichelson We decided that they do not since the place has a URI and we couldn't think of any reason why someone would need to point to the collection of data on the place without pointing to the whole TEI document ([uri]/tei). Do you want to revisit this?

**Comment by davidamichelson** [comment]
It will crash the webhooks
