### ISSUE TITLE
Remove Syriaca.org as sponsor

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#24]
@davidamichelson Most (all?) of the <5000 range records have Syriaca.org as one of the sponsors, but I believe we decided not to include this (see, e.g. [https://bqgazetteer.bethmardutho.org/place/5400](url)). We can find-and-replace to remove this sponsor element.

**Comment by davidamichelson** [comment]
I think it is the reverse we are intending to include it.

**Comment by davidamichelson** [comment]
Please check all records and if they don't have Syriaca.org then add it.
