### ISSUE TITLE
Update @ref values in abstracts to point to BQ Gazetteer records

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#25]
Currently, the ref pointers in nested placeName elements point to Syriaca records. These should point at BQ place records.

See, for example, place 3001: 
`<desc type="abstract" xml:lang="en" xml:id="abstract3001-1">A city of <placeName
              ref="http://syriaca.org/place/603">Khurasan</placeName> between <placeName
              ref="http://syriaca.org/place/2997">Naysābūr</placeName> and <placeName
              ref="http://syriaca.org/place/607">Merv</placeName>
          </desc>`

Which would become:
`<desc type="abstract" xml:lang="en" xml:id="abstract3001-1">A city of <placeName
              ref="http://bqgazetteer.bethmardutho.org/place/603">Khurasan</placeName> between <placeName
              ref="http://bqgazetteer.bethmardutho.org/place/2997">Naysābūr</placeName> and <placeName
              ref="http://bqgazetteer.bethmardutho.org/place/607">Merv</placeName>
          </desc>`

Likely can be a find-and-replace, but we will need to figure out if these occur outside of the placeName elements as well.

**Comment by wlpotter** [comment]
One of the things we'll have to deal with is that some placeNames point to records that aren't in the BQ Gazetteer. An example of this would be place 2999 whose abstract references place 526, in the Syriaca Gazetteer but not in the BQ Gazetteer.

**Comment by wlpotter** [comment]
Woops! This is the same as #4

**Comment by davidamichelson** [comment]
We will ask Winona to write a script to check for dead @refs URLs and find and replace them.

**Comment by davidamichelson** [comment]
Leave this open when you are done with find and replace so we can ask Winona to write this script.

**Comment by davidamichelson** [comment]
@wlpotter , wait on this until we can discuss how to implement the linked data solution we need

**Comment by davidamichelson** [comment]
Ok go ahead with this find and replace.

**Comment by wlpotter** [comment]
There was only record with a tei:desc/@ref that pointed to the BQG rather than the Syriaca one. I changed it to Syriaca for consistency. We will need to find-and-replace to construct the links if we are planning on using the same method that e-GEDSH uses, e.g.:

```
<ref rend="bold" target="https://gedsh.bethmardutho.org/Harran">
<placeName ref="http://syriaca.org/place/216">Ḥarran</placeName>
</ref>
```
The target in the tei:ref element would of course point to the BQG URI, not GEDSH. I am waiting to make this change until we've confirmed this is the method we want to use.

**Comment by wlpotter** [comment]
The data has been updated to this format; the app will need to handle this change so that the links follow the `<ref>` rather than the `@ref`. Currently it still points to Syriaca.org

We will also need a script that checks for dead BQG links and redirect them to the Syriaca Gazetteer.

**Comment by wlpotter** [comment]
This should be fixed now.

**Comment by davidamichelson** [comment]
@wsalesky @wlpotter @dlschwartz
We have to reopen this because we found another case that needs special attention.

So we have done TEI:desc this way:
```
<desc>Ayban was a settlement the district of <ref target="https://bqgazetteer.bethmardutho.org/place/5573"><placeName ref="http://syriaca.org/place/5573">ʿAdan Abyan</placeName></ref></desc>
```
But how should we handle nested locations?
Currently:
```    
<location type="nested">
<region ref="https://bqgazetteer.bethmardutho.org/place/5573">ʿAdan Abyan</region>
</location>
```
But could be:
```
<location type="nested">
<ref target="https://bqgazetteer.bethmardutho.org/place/5573">
<region ref="http://syriaca.org/place/5573">ʿAdan Abyan</region>
</ref>
</location>
```
or probably better TEI but less consistent with our earlier solution?
```
<location type="nested">
<region ref="https://bqgazetteer.bethmardutho.org/place/5573">
<placeName ref="http://syriaca.org/place/5573">ʿAdan Abyan</placeName>
</region>
</location>
```
I like choice two, Winona would that work?

Thanks,
DM

**Comment by wsalesky** [comment]
@davidamichelson either works for me.

**Comment by dlschwartz** [comment]
@davidamichelson I like choice two as well. If that works for Winona I would go with that.

**Comment by davidamichelson** [comment]
Okay we will go with choice two! Will can you please insert?

**Comment by wlpotter** [comment]
Data has been changed
