### ISSUE TITLE
add periods to all descs that do not have one

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#39]

**Comment by davidamichelson** [comment]
Will need to wait until we get advice on #53

**Comment by wlpotter** [comment]
This should be fixed. All the (English-language) descs that do are unquoted (i.e. do not have a child tei:quote element) have periods now.

The ones that were quoted all had periods (except for 2907, which I added manually), most of them right before the closing tag of the tei:quote element but a few right before the closing tag of the tei:desc. (I was able to find any issues once I removed any leading whitespace on the tei:desc's closing tag). @davidamichelson Do we have a preference for where the period should be? It shouldn't be a hard fix to regularize them if we need to.

This doesn't fix issue #53 which I'm still a bit stumped on solving. But the descs should all have periods now. 

Note that we may also need to add periods to Arabic and/or Syriac language descs. I've not checked these
