### ISSUE TITLE
Place 5405 (Qaba') abstract citation

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#42]
https://bqgazetteer.bethmardutho.org/place/5405

The abstract is: A city in Farghana, “a valley on the middle Jaxartes (Si̊r-Daryā), approximately 300 km.” (W. Barthold and B. Spuler).

The quote, though, is from the article on Farghana, not Qaba'. Need new abstract?

Relatedly, need record for Farghana?

**Comment by davidamichelson** [comment]
Fixed. Farghana will be added from Syriac world.
