### ISSUE TITLE
Place 5459 needs an abstract written

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#43]
https://bqgazetteer.bethmardutho.org/place/5459

Same issue type of as #41 but no Encyclopaedia of Islam article to reference.

**Comment by davidamichelson** [comment]
Need to ask Mario. Which Shahristan is this? http://whc.unesco.org/en/tentativelists/1387/ or https://pleiades.stoa.org/places/29755/ram-shahrestan or https://pleiades.stoa.org/places/29755

**Comment by davidamichelson** [comment]
Mario, Should we keep this entry or delete it?

**Comment by wlpotter** [comment]
This was Mario's response on this: 
"Let's leave Shahristan off the map for the time being until I have time to check all the references."

It is still in the db; not sure if we want to delete it (temporarily??)

**Comment by davidamichelson** [comment]
delete place

**Comment by wlpotter** [comment]
Remove record 5459 from db.

Note: keep for Syriaca Gazetteer?

**Comment by wlpotter** [comment]
5459 deleted from db. Leaving this issue open until we decide if we want the record to be included in the Syriac Gazetteer.
