### ISSUE TITLE
Place 5218 English brief desc needs attention

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#44]
https://bqgazetteer.bethmardutho.org/place/5218 has an unsourced desc referring to page 298 of an unknown source - perhaps Encyclopaedia of Islam, Third Edition? However, the quote "Bādghīs consists of eight cities inlcuding Dahistān, Kughānābādh, Kūfā, Busht, Jādhāwā, Kābrūn, Kālawūn and Jabal al-Fiḍḍa" cannot be found via searching EI3 on Brill. 

Possibly just delete this description

**Comment by davidamichelson** [comment]
Deleted.
