### ISSUE TITLE
Syncing a local install of eXist-db with Github

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#46]
@wsalesky I am working on the Beth Qatraye data in a local eXist installation. I ran a script in eXide that changed some of the records (but not all). Unfortunately, it seems eXist is changing the whitespace on the records when they are uploaded, so GitHub is recognizing a lot more changes than the script makes. I'd like to find a way to first bring eXist up-to-date with the GitHub repository before executing the script.

I had tried setting eXide up to sync with my clone of the GitHub repository (using the Application>Synchronize function). I ran this sync before executing the script, thinking this would bring the eXist copy up-to-date with the GitHub copy. However, after I run the script and then "synchronize" then "apply", my GitHub desktop client still recognizes white-space changes.

Am I on the right track? Or is there another way to first bring the eXist versions up to date with GitHub before running the script in eXide?

Below is the menu I am using in eXide to (try to) synchronize: 

![Screen Shot 2019-12-11 at 3 51 10 PM](https://user-images.githubusercontent.com/44096602/70663650-682bdd80-1c2e-11ea-8ae3-c84053f361c7.png)

**Comment by wsalesky** [comment]
@wlpotter how are you loading them into the database? I use the webdav client via oXygen to upload and download. Another option is to check your exist-db conf.xml look up the settings for the indexer, make sure your  preserve-whitespace-mixed-content attribute is set to 'yes'. On my mac using the installer the conf file for my 5.0 version of the db is located :  `/Applications/eXist-db-5.0.app/Contents/Resources/etc`  

Let me know if either of those help.

**Comment by wlpotter** [comment]
Yes, these helped. I was able to load them into oXygen using to the webdav client which let me commit the whitespace changes first, bringing Github in line with exist-db. That let me run the xquery and make a clear commit of those changes. Thanks!
