### ISSUE TITLE
Hajar records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#55]
Check out https://bqgazetteer.bethmardutho.org/place/5289 and https://bqgazetteer.bethmardutho.org/place/2903 and email from Mario

**Comment by wlpotter** [comment]
Change the URI for one or both of these records to 4155 once this is sorted out (see #49 )

**Comment by wlpotter** [comment]
See also https://github.com/srophe/bethqatraye-data/commit/8bfb2ce964388fbb05ecee169fb4d3018d10beec

**Comment by wlpotter** [comment]
Need to reopen this to add the following note from Mario:
***
 In Arabic sources referred to as Hajar, al-Ḥasāʾ or al-Aḥsāʾ: Ibn al-Faqīh, Kitāb al-Buldān 30; Ibn Khuradādhbih, Kitāb al-Masālik 152; Yāqūt, Muʿjam al-buldān i, 112; al-Masʿūdī, Murūj v, 242; al-Bakrī, Kitāb al-Masālik i, 371, 377; Nāṣir Khusraw, Safar Nāma 159; al-Ṭabarī, Taʾrīkh ii, 839.

From my forthcoming article (no volume title/Publisher yet): "The Maritime Journey of Catholicos Giwargis I (d. 680 CE) to the East-Arabian Island of Dayrīn and the “Islands.”"
***
The only citation not accounted for in this note is Yāqūt, Muʿjam al-buldān i, 112. We have a citation from v, 393. There is a reference in the original google sheet to al-ahsa "a water" that cites Mu'jam al-buldan i, 111-112. This should likely be included in this record.

@davidamichelson I know this should become a `<note>` but am unsure what type it should be - incerta?

**Comment by wlpotter** [comment]
Will also need to create a bibl record for the forthcoming article that Mario refers to.

**Comment by wlpotter** [comment]
An update on what remains to be done here:

1. Add zotero and Syriaca bibl records for Mario's forthcoming article?
2. Link the citations in the note from Mario to the bibls in the record.
