### ISSUE TITLE
HTTPS or HTTP?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#60]
@wsalesky It seems we have some URIS as  https: and some as http:

Ex:  https://bqgazetteer.bethmardutho.org/place/2982

What did we decide? I think we decided on HTTPS? I will change the data to be uniform, but please let me know if HTTPS is fine.

Will that break any scripts?

**Comment by wsalesky** [comment]
@davidamichelson It should not cause any issues as long as the base-uri declared here: https://github.com/srophe/bethqatraye/blob/master/repo-config.xml#L30 matches.

**Comment by davidamichelson** [comment]
Hmm, there seems to be both https and http in there. Compare lines 22 and 30

https://github.com/srophe/bethqatraye/blob/50a6fcc4624adda190318620ae5af628fb831451/repo-config.xml#L22-L30

Should we use HTTPS for everything?

**Comment by wsalesky** [comment]
Looks like a bad merge there should only be one. I'm fine using https.

**Comment by davidamichelson** [comment]
Okay, HTTPS it is!

**Comment by davidamichelson** [comment]
Could you please change the code in the app to HTTPS and I will change the code in the data to HTTPS.

**Comment by davidamichelson** [comment]
I will let you know when I am done.

**Comment by davidamichelson** [comment]
Okay just pushed new data, but wait for an e-mail from me.

**Comment by davidamichelson** [comment]
Oops, will leave open until you change in the app

**Comment by wsalesky** [comment]
Done!
