### ISSUE TITLE
Updates to the geography schema

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#69]
See https://github.com/srophe/bethqatraye-data/issues/3

**Comment by wlpotter** [comment]
@dlschwartz I've compiled a list of the remaining schema changes we would like

- allow `@subtype="representative"` on tei:location elements (full xpath: /TEI/text/body/listPlace/place/location). See #3 
- the `@resp` attribute, which is now allowed on both tei:placeName and tei:location elements, should allow the attribute value to be the string "https://bqgazetteer.bethmardutho.org". For tei:location elements, this seems to be true. However, on tei:placeName elements, `@resp="https://bqgazetteer.bethmardutho.org"` is invalid (the schema expects only the string "http://syriaca.org")
- The schema says that tei:principal is 'not allowed anywhere'. We would like to include this in the tei:titleStmt (full xpath: /TEI/teiHeader/fileDesc/titleStmt/principal). This element follows the tei:funder and precedes the tei:editor elements.
- The schema expects a tei:seriesStmt, which the BQG records will not have. 

Please let me know if any of the above is unclear. Thanks much!

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson A quick initial test suggests that [this commit](https://github.com/srophe/draft-data/commit/aa2b9658551f5a152c02d1cbddb3480d726ee6b3) resolves the changes requested here. Can you please test this a bit more widely and let me know if you need any additional changes. You can close the issue when you're satisfied.

**Comment by wlpotter** [comment]
@dlschwartz I checked a couple more records, and this looks to be fixed. Thanks!

**Comment by wlpotter** [comment]
Reopening to remind myself to break these out into "everywhere" and "bqg-specific" changes and making separate issues for each.

**Comment by wlpotter** [comment]
These have been split out into
#74 #75 #76 and #77
