### ISSUE TITLE
New Map Grouping

### ISSUE THREAD

**Issue by davidamichelson** [srophe/bethqatraye-data#70]
@wsalesky we would like to port this feature to DBQ https://github.com/srophe/caesarea/issues/28#event-3181122155 please!

@wlpotter can you edit the data please to fit?

**Comment by davidamichelson** [comment]
After you fit the data then make an issue for @wsalesky in the BQG app

**Comment by wlpotter** [comment]
Data is ready for the port; new issue has been made for the BQG app (https://github.com/srophe/bethqatraye/issues/71)
