### ISSUE TITLE
schema updates from BQG records

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#73]
The following changes are being proposed to the schema based on batch validating the Beth Qatraye records. 

- allow "vol" as a value for the `@unit` attribute on tei:citedRange elements to specify the volume information of a given bibliographic source. See, e.g. https://bqgazetteer.bethmardutho.org/place/105#bib105-4
- allow the values "contributing" and "technical" for the `@role` attribute on tei:editor elements. For BQG records, Thomas A. Carlson is listed as a contributing editor, and David A. Michelson and William L. Potter are listed as technical editors. Note that we are also using "technical" as a value for this attribute in the [Caesarea Maritima project](https://github.com/srophe/caesarea-data)
- allow a tei:choice element within a tei:quote element (full path: /TEI/text/body/listPlace/place/desc/quote/choice) so we can mark typos in quoted sources, as in this example: https://bqgazetteer.bethmardutho.org/place/2994. See the related display issue here: https://github.com/srophe/bethqatraye/issues/72
- allow tei:ref elements as children of `tei:location[@type="relative]` (full path: /TEI/text/body/listPlace/place/location). See, for example https://bqgazetteer.bethmardutho.org/place/4156. See [this comment](https://github.com/srophe/bethqatraye-data/issues/25#issuecomment-562642780) in related issue #25.
- allow values "valley" and "cemetery" for `@type` attribute on tei:place elements. A related issue will address updating the documentation and place-type lists for these two new place types. See, https://bqgazetteer.bethmardutho.org/place/5045 for an example of "cemetery" and https://bqgazetteer.bethmardutho.org/place/5518 for an example of "valley". 

Please post questions and discussion as needed.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson I've been thinking that our place types should get URIs instead of the status quo. Would this be a time to make that change or should we simply update the current list and move everything to URIs down the line when the taxonomy develops?

**Comment by wlpotter** [comment]
To clarify the issue with the tei:ref elements as children of tei:location: this is not associated with [the bibl issue](https://github.com/srophe/srophe-app-data/issues/781). Rather, the use of tei:ref elements with `@target` attributes pointing to place URIs facilitates internal hyperlinking, i.e. within the BQG, and linked data with the Syriac Gazetteer records. The TEI for the example looks like this:

```
<location type="relative" source="#bib4156-6">A city located 
    <measure unit="farasikh" quantity="7">seven farsakh</measure>
    <offset>north of</offset> 
    <ref target="https://bqgazetteer.bethmardutho.org/place/4155">
        <placeName ref="http://syriaca.org/place/4155">al-Aḥsāʾ</placeName>
     </ref> 
...
</location>
```
See, still, the discussion in #25 

Since this solution was specific to the BQG, the schema change will not need to be ported to the Syriac Gazetteer schema. (this of course raises the question of when and how we will want to split off the BQG schema from the general schema).

**Comment by davidamichelson** [comment]
@dlschwartz We would like to discuss with you the difference between the generic Srophe schema and Syriaca's schema and if we want them to differ and if so how much

**Comment by wlpotter** [comment]
These have been broken out into
#78 #79 #80 #81 and #82

See those issues for further discussion.
