### ISSUE TITLE
allow @subtype="representative" on tei:location elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#74]
Full path: /TEI/text/body/listPlace/place/location). See #3

@dlschwartz this change may already have been made, but opening an issue just to confirm. Close if this is the case.

Cf. [this commit](https://github.com/srophe/draft-data/commit/aa2b9658551f5a152c02d1cbddb3480d726ee6b3), which likely included this change.

**Comment by wlpotter** [comment]
Cf. https://github.com/srophe/srophe-app-data/issues/795

**Comment by dlschwartz** [comment]
@wlpotter this should work properly. Is this still an issue?

**Comment by wlpotter** [comment]
This is working, thanks!
