### ISSUE TITLE
allow "vol" as a value for the @unit attribute on tei:citedRange elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#78]
allow "vol" as a value for the @unit attribute on tei:citedRange elements to specify the volume information of a given bibliographic source. See, e.g. https://bqgazetteer.bethmardutho.org/place/105#bib105-4

@dlschwartz this change is being proposed for both the BQG and the general Syriaca schema.

**Comment by dlschwartz** [comment]
@wlpotter please test and close.

**Comment by wlpotter** [comment]
This is working, thanks!
