### ISSUE TITLE
allow a tei:choice element within a tei:quote element

### ISSUE THREAD

**Issue by wlpotter** [srophe/bethqatraye-data#80]
allow a tei:choice element within a tei:quote element (full path: /TEI/text/body/listPlace/place/desc/quote/choice) so we can mark typos in quoted sources, as in this example: https://bqgazetteer.bethmardutho.org/place/2994. See the related display issue here: srophe/bethqatraye#72

@dlschwartz this is being proposed as a schema change for both BQG and the general Syriaca schema.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson I've added choice as well as abbr, corr, expan, orig, reg, and sic. Please test this and close the issue if it works as expected.

**Comment by wlpotter** [comment]
This works, thanks!
